name: Update Stock Data

on:
  schedule:
    # Run at 5:00 PM ET (22:00 UTC) on weekdays
    - cron: '0 22 * * 1-5'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths: 
      - 'scripts/fetch-data.js'
      - '.github/workflows/update-data.yml'

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Fetch stock data
      env:
        IEX_API_KEY: ${{ secrets.IEX_API_KEY }} # Actually contains Polygon.io API key
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      run: node scripts/fetch-data.js
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/stocks.json
        git commit -m "Update stock data - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push
    
    - name: Deploy to GitHub Pages
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,scripts,node_modules,package*.json,README.md'